services:
  cometmarketplace-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5006:5432'
    volumes:
      - commetmarketplace-db:/var/lib/postgresql/data
volumes:
  commetmarketplace-db:
    driver: local
